### PR TITLE
Microsite

### PR DESCRIPTION
**Pull request by gvolpe**
As I promised I created an initial microsite setup with some docs. Still more to be added! :tada: 

home

guide

### CODE REVIEW

**Comment by pchlupacek** [comment]
@gvolpe excellent this is great :-)

**Comment by gvolpe** [comment]
@pchlupacek I have an idea. This project needs more recognition (eg. more stars) since it's amazing. 

I believe that didn't become very popular on one hand because there are not too many developers who are familiar with `fs2` (though we are becoming more and more :tada: ) and mainly because of the lack of documentation (though it's very well tested).

`http4s` and some other projects have been gaining a lot of new contributions after publishing it on `Twitter` and creating issues labelled as `good first issue` and `help wanted`. The impact was quite big.

IMO this will incentivize people to contribute and give the project the recognition it deserves by sharing it :)

I'm not sure how much more I'd be able to contribute to the docs since time is very limited these days but I'm willing to create these `good first time` issues and share to get more contributors.

What do you think?

Some work on your side needs to be done in order to set up the publishing of the microsite but I can help you with it since I've learned the process after publishing several sites :)

**Comment by pchlupacek** [comment]
@gvolpe Thanks for ideas and suggestions. I think it would be excellent if you would be able to take a lead on this. I can give you collaborator access so you may be flexible there. Would that work for you?

**Comment by gvolpe** [comment]
@pchlupacek awesome, go for it :smiley: I'll set up the issues as soon as I find some free time.

**Comment by gvolpe** [comment]
@pchlupacek I texted you on the Gitter channel of `fs2-cassandra`, not sure if you guys are active there :smile:

**Comment by gvolpe** [comment]
@pchlupacek the `Travis` build is now passing, I consider this ready to be merged so I can publish the microsite and start hunting new contributors! (I already got one interested) :smile:

**Comment by pchlupacek** [comment]
@gvolpe this looks great. Merging.

**Pull request merged**
